web_scraping:
  start_page: https://www.currys.co.uk/appliances/refrigeration/fridges
  product_selector: ".row.plp-list-grid"
  product_name_selector: ".pdp-grid-product-name"
  product_price_selector: ".value"
  product_grade_selector: ".curry-sansreg-headline"
